spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_wallet_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: digital-wallet
server:
  port: 8080
